# Generated by Django 4.2.7 on 2023-12-08 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('Sno', models.BigIntegerField(primary_key=True, serialize=False)),
                ('State_name', models.CharField(max_length=100)),
                ('Capital', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('Cno', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Capital_name', models.CharField(max_length=3)),
                ('Population', models.BigIntegerField()),
                ('Sno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.state')),
            ],
        ),
    ]
