# Generated by Django 4.2.7 on 2023-12-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capital',
            name='Capital_name',
            field=models.CharField(max_length=100),
        ),
    ]
