# Generated by Django 4.2.7 on 2023-12-13 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_capital_capital_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capital',
            old_name='Sno',
            new_name='Sname',
        ),
    ]
